name: Deploy to cloudtype
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: skfla2459/mariadb
          stage: main
          yaml: |
            name: checklist
            app: java@17
            options:
              ports: 8080
              env:
                - name: DB_url
                  value: svc.sel4.cloudtype.app
                - name: DB_port
                  value: "32589"
                - name: DB_dataBaseName
                  value: challenge
                - name: DB_name
                  value: root
                - name: DB_password
                  value: "1234"
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: java-springboot
